openapi: 3.0.0

info:
  title: Quản lí Tác vụ
  description: API quản lý nhiệm vụ với xác thực JWT
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: http://localhost:5000

tags:
  - name: Auth
    description: Xác thực người dùng
  - name: Tasks
    description: Quản lý nhiệm vụ

components:
  securitySchemes:
    BearerAuth:
      type: http #Xác thực thông qua header
      scheme: bearer # scheme là Bearer
      bearerFormat: jwt #Token là JWT

  responses:
    UnauthorizedError:
      description: Không có token hoặc token không hợp lệ
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 401
              message:
                type: string
                example: Unauthorized
              data:
                nullable: true

paths:
  /login:
    post:
      summary: Đăng nhập
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: "admin"
                password:
                  type: string
                  example: "123456"
      responses:
        "200":
          description: Trả về token JWT và đăng nhập thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                  message:
                    type: string
                  status:
                    type: integer

  /tasks:
    get:
      summary: Lấy toàn bộ danh sách nhiệm vụ
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Trả về toàn bộ nhiệm vụ của người dùng
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        status:
                          type: string
                  message:
                    type: string
                  status:
                    type: integer

        "401":
          $ref: "#/components/responses/UnauthorizedError"

    post:
      summary: Tạo một nhiệm vụ mới
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
      responses:
        "201":
          description: Trả về nhiệm vụ đã được tạo
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      status:
                        type: string
                  message:
                    type: string
                  status:
                    type: integer

        "401":
          $ref: "#/components/responses/UnauthorizedError"

  /tasks/{task_id}:
    get:
      summary: Lấy chi tiết 1 nhiệm vụ
      security:
        - BearerAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Trả về chi tiết 1 nhiệm vụ
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      status:
                        type: string
                  message:
                    type: string
                  status:
                    type: integer
        "404":
          description: Không tìm thấy nhiệm vụ có id như trên
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
        "401":
          $ref: "#/components/responses/UnauthorizedError"

    put:
      summary: Cập nhật nhiệm vụ
      security:
        - BearerAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                status:
                  type: string
      responses:
        "200":
          description: Trả về thông tin nhiệm vụ sau khi cập nhật
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      status:
                        type: string
                  message:
                    type: string
                  status:
                    type: integer
        "404":
          description: Không tìm thấy nhiệm vụ có id như trên
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
        "401":
          $ref: "#/components/responses/UnauthorizedError"

    delete:
      summary: Xóa nhiệm vụ có trong hệ thống
      security:
        - BearerAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Xóa thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    nullable: true
                  message:
                    type: string
                  status:
                    type: integer

        "404":
          description: Không tìm thấy nhiệm vụ có id như trên
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
        "401":
          $ref: "#/components/responses/UnauthorizedError"
